workflows:
  capacitor-ios:
    name: Capacitor iOS Workflow
    max_build_duration: 120
    environment:
      groups:
        - app_store_connect
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"  # Ajuste se o caminho do workspace for diferente
        XCODE_SCHEME: "App"                          # Ajuste para o seu Xcode Scheme
      xcode: latest
      node: 20.5.1  # Node >=20 é necessário para o Capacitor
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Build iOS
        script: |
          xcode-project build-ipa
    artifacts:
      - build/ios/ipa/*.ipa
