workflows:
  ios-release-experimental:
    name: iOS Release to TestFlight

    environment:
      xcode: latest
      node: 20.9.0

      ios_signing:
        provisioning_profiles:
          - AgriRoute

    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm run build

      - name: Install CocoaPods
        script: |
          cd ios && pod install --repo-update

      - name: Build iOS .ipa
        script: |
          cd ios
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -archivePath build/App.xcarchive \
            archive

          xcodebuild \
            -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build \
            -exportOptionsPlist exportOptions.plist

    artifacts:
      - ios/build/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

        submit_to_testflight: true
