workflows:
  ios-release-testflight:
    name: iOS Release to TestFlight
    environment:
      xcode: latest
      node: 20.9.0
      ios_signing:
        distribution_type: app_store
        bundle_identifier: app.lovable.f2dbc20153194f90a3cc8dd215bbebba
    scripts:
      - name: Install dependencies
        script: |
          npm install
      
      - name: Build web app
        script: |
          npm run build
      
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      
      - name: Install CocoaPods
        script: |
          cd ios/App && pod install
      
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files \
            "app.lovable.f2dbc20153194f90a3cc8dd215bbebba" \
            --type IOS_APP_STORE \
            --create
      
      - name: Set up keychain
        script: |
          keychain initialize
      
      - name: Add certificates
        script: |
          app-store-connect add-certificates --type IOS_APP_STORE
      
      - name: Install provisioning profiles
        script: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          find $(pwd) -name "*.mobileprovision" -exec cp {} ~/Library/MobileDevice/Provisioning\ Profiles/ \;
      
      - name: Build IPA for App Store
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App \
            --export-options-plist ios/App/exportOptions.plist
    
    artifacts:
      - build/ios/ipa/*.ipa
