workflows:
  capacitor-ios:
    name: Capacitor iOS Workflow
    max_build_duration: 120
    environment:
      groups:
        - app_store_connect
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "app.lovable.f2dbc20153194f90a3cc8dd215bbebba"
      xcode: latest
      node: 20.9.0
    scripts:
      - name: Fix and install dependencies
        script: |
          echo "🔧 Resolvendo problemas de dependências..."
          rm -f package-lock.json
          npm install --legacy-peer-deps --no-audit
          echo "✅ Dependências instaladas com sucesso!"

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App && pod install

      - name: Fix iOS project signing
        script: |
          echo "🔧 Corrigindo configuração do projeto iOS..."
          cd ios/App
          
          # Corrigir DEVELOPMENT_TEAM duplicado usando Python
          python3 -c "
          import re
          with open('App.xcodeproj/project.pbxproj', 'r') as f:
              content = f.read()
          
          # Remover DEVELOPMENT_TEAM duplicado
          content = re.sub(r'DEVELOPMENT_TEAM = 4YULT95XAK;\s*DEVELOPMENT_TEAM = 4YULT95XAK;', 'DEVELOPMENT_TEAM = 4YULT95XAK;', content)
          
          # Garantir CODE_SIGN_STYLE = Automatic
          content = content.replace('CODE_SIGN_STYLE = Manual;', 'CODE_SIGN_STYLE = Automatic;')
          
          with open('App.xcodeproj/project.pbxproj', 'w') as f:
              f.write(content)
          "
          echo "✅ Projeto iOS corrigido!"

      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "" \
            --type IOS_APP_DEVELOPMENT \
            --create

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Build iOS
        script: |
          xcode-project build-ipa \
            --workspace "" \
            --scheme ""

    artifacts:
      - build/ios/ipa/*.ipa
