workflows:
  capacitor-ios:
    name: Capacitor iOS Workflow
    max_build_duration: 120
    environment:
      groups:
        - app_store_connect   # Certifique-se de que você configurou o App Store Connect API Key neste grupo
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      xcode: latest
      node: 20.5.1
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Build iOS
        script: |
          xcode-project build-ipa --workspace $XCODE_WORKSPACE --scheme $XCODE_SCHEME --automatic-code-signing
    artifacts:
      - build/ios/ipa/*.ipa
