workflows:
  capacitor-ios:
    name: Capacitor iOS Workflow
    max_build_duration: 120
    environment:
      groups:
        - app_store_connect
      vars:
        XCODE_WORKSPACE: "ios/App/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      xcode: latest
      node: 20.5.1
    scripts:
      - name: Discover project structure
        script: |
          echo "=== PROJECT STRUCTURE ==="
          find . -name "*.xcworkspace" -o -name "*.xcodeproj" -o -name "capacitor.config.*" | head -20
          echo "=== IOS FOLDER ==="
          ls -la ios/ 2>/dev/null || echo "No ios folder at root"
          echo "=== APP FOLDER ==="
          ls -la ios/App/ 2>/dev/null || echo "No ios/App folder"
          echo "=== CAPACITOR CONFIG ==="
          cat capacitor.config.ts 2>/dev/null || cat capacitor.config.json 2>/dev/null || echo "No capacitor config found"
          echo "=== PACKAGE.JSON ==="
          cat package.json | grep -A 5 "capacitor"
      
      - name: Install dependencies
        script: |
          npm install
      
      - name: Build web app
        script: |
          npm run build
      
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      
      - name: Install CocoaPods
        script: |
          cd ios/App && pod install
      
      - name: Build iOS
        script: |
          cd ios/App/App
          xcode-project build-ipa --workspace "App.xcworkspace" --scheme "App"
    
    artifacts:
      - build/ios/ipa/*.ipa
