workflows:
  ios-release-testflight:
    name: iOS Release to TestFlight
    environment:
      xcode: latest
      node: 20.9.0
    scripts:
      - name: Install dependencies
        script: |
          npm install
      
      - name: Build web app
        script: |
          npm run build
      
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      
      - name: Install CocoaPods
        script: |
          cd ios/App && pod install
      
      - name: Build IPA with Codemagic Signing
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App \
            --export-options-plist ios/App/exportOptions.plist
    
    artifacts:
      - build/ios/ipa/*.ipa
