workflows:
  ios-release-testflight:
    name: iOS Release to TestFlight
    environment:
      xcode: latest
      node: 20.9.0
    scripts:
      - name: Install dependencies
        script: |
          npm install
      
      - name: Build web app
        script: |
          npm run build
      
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      
      - name: Install CocoaPods
        script: |
          cd ios/App && pod install
      
      - name: Build with Automatic Provisioning
        script: |
          cd ios/App
          rm -rf build
          
          xcodebuild archive \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            -allowProvisioningUpdates \
            -destination 'generic/platform=iOS'
          
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/ipa \
            -allowProvisioningUpdates
          
          echo "=== IPA Gerado ==="
          ls -la build/ipa/
    
    artifacts:
      - ios/App/build/ipa/*.ipa
