workflows:
  capacitor-ios:
    name: Capacitor iOS Workflow
    max_build_duration: 120
    environment:
      xcode: latest
      node: 20.9.0
    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App && pod install

      - name: Build iOS App
        script: |
          cd ios/App
          
          # Criar export options
          cat > export_options.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>teamID</key>
              <string>4YULT95XAK</string>
              <key>signingStyle</key>
              <string>automatic</string>
          </dict>
          </plist>
          EOF

          # Build simples e direto
          xcodebuild clean archive \
            -workspace App.xcworkspace \
            -scheme App \
            -archivePath build/App.xcarchive \
            -allowProvisioningUpdates

          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist export_options.plist \
            -allowProvisioningUpdates

    artifacts:
      - ios/App/build/ipa/*.ipa
