workflows:
  capacitor-ios:
    name: Capacitor iOS Workflow
    max_build_duration: 120
    environment:
      xcode: latest
      node: 20.9.0
    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App && pod install

      - name: Configure iOS Project for Unsigned Build
        script: |
          cd ios/App
          
          # DESATIVAR ASSINATURA COMPLETAMENTE
          python3 -c "
          import re
          
          with open('App.xcodeproj/project.pbxproj', 'r') as f:
              content = f.read()
          
          # 1. Desativar assinatura de código
          content = re.sub(r'CODE_SIGN_STYLE = .*;', 'CODE_SIGN_STYLE = Manual;', content)
          content = re.sub(r'CODE_SIGNING_ALLOWED = .*;', 'CODE_SIGNING_ALLOWED = NO;', content)
          content = re.sub(r'CODE_SIGNING_REQUIRED = .*;', 'CODE_SIGNING_REQUIRED = NO;', content)
          content = re.sub(r'PROVISIONING_PROFILE_SPECIFIER = \".*\";', 'PROVISIONING_PROFILE_SPECIFIER = \"\";', content)
          content = re.sub(r'DEVELOPMENT_TEAM = \".*\";', 'DEVELOPMENT_TEAM = \"\";', content)
          content = re.sub(r'CODE_SIGN_IDENTITY = \".*\";', 'CODE_SIGN_IDENTITY = \"\";', content)
          
          with open('App.xcodeproj/project.pbxproj', 'w') as f:
              f.write(content)
          "
          echo "✅ Assinatura desativada para build!"

      - name: Build iOS App Without Signing
        script: |
          cd ios/App
          
          echo "📱 Iniciando build iOS SEM assinatura..."
          
          # Build SEM assinatura
          xcodebuild clean build \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            DEVELOPMENT_TEAM=""

          echo "✅ Build concluído!"

          # Criar IPA manualmente sem assinatura
          mkdir -p build/ipa/Payload
          cp -r build/Build/Products/Debug-iphoneos/App.app build/ipa/Payload/
          cd build/ipa
          zip -r App.ipa Payload
          
          echo "🎉 IPA criado manualmente!"
          ls -la

    artifacts:
      - ios/App/build/ipa/*.ipa
