workflows:
  capacitor-ios:
    name: Capacitor iOS Workflow
    max_build_duration: 120
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "app.lovable.f2dbc20153194f90a3cc8dd215bbebba"
        DEVELOPMENT_TEAM: "4YULT95XAK"
      xcode: latest
      node: 20.9.0
    scripts:
      - name: Fix and install dependencies
        script: |
          echo "🔧 Resolvendo problemas de dependências..."
          rm -f package-lock.json
          npm install --legacy-peer-deps --no-audit
          echo "✅ Dependências instaladas com sucesso!"

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App && pod install

      - name: Configure iOS Automatic Signing
        script: |
          echo "🔧 Configurando assinatura automática..."
          cd ios/App
          
          # Corrigir DEVELOPMENT_TEAM duplicado e configurar assinatura automática
          python3 -c "
          import re
          with open('App.xcodeproj/project.pbxproj', 'r') as f:
              content = f.read()
          
          # Remover DEVELOPMENT_TEAM duplicado
          content = re.sub(r'DEVELOPMENT_TEAM = 4YULT95XAK;\s*DEVELOPMENT_TEAM = 4YULT95XAK;', 'DEVELOPMENT_TEAM = 4YULT95XAK;', content)
          
          # Garantir CODE_SIGN_STYLE = Automatic
          content = content.replace('CODE_SIGN_STYLE = Manual;', 'CODE_SIGN_STYLE = Automatic;')
          
          # Se não tiver CODE_SIGN_STYLE, adicionar
          if 'CODE_SIGN_STYLE = Automatic;' not in content:
              content = content.replace('buildSettings = {', 'buildSettings = {\n\t\t\t\tCODE_SIGN_STYLE = Automatic;')
          
          with open('App.xcodeproj/project.pbxproj', 'w') as f:
              f.write(content)
          "
          echo "✅ Assinatura automática configurada!"

      - name: Build iOS with Automatic Signing
        script: |
          cd ios/App
          
          # Criar export options para desenvolvimento
          cat > export_options.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>teamID</key>
              <string></string>
              <key>signingStyle</key>
              <string>automatic</string>
          </dict>
          </plist>
          EOF

          echo "📱 Iniciando build iOS com assinatura automática..."
          
          # Tentar build com assinatura automática
          xcodebuild clean archive \
            -workspace App.xcworkspace \
            -scheme App \
            -archivePath build/App.xcarchive \
            -allowProvisioningUpdates \
            DEVELOPMENT_TEAM="" \
            CODE_SIGN_STYLE=Automatic \
            PRODUCT_BUNDLE_IDENTIFIER="" || echo "⚠️ Archive falhou, tentando sem provisioning updates..."

          # Tentar novamente se falhar
          xcodebuild clean archive \
            -workspace App.xcworkspace \
            -scheme App \
            -archivePath build/App.xcarchive \
            DEVELOPMENT_TEAM="" \
            CODE_SIGN_STYLE=Automatic \
            PRODUCT_BUNDLE_IDENTIFIER=""

          echo "✅ Archive concluído!"

          # Exportar IPA
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist export_options.plist \
            -allowProvisioningUpdates || echo "⚠️ Export falhou, tentando sem provisioning updates..."

          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist export_options.plist

          echo "🎉 Build iOS concluído com sucesso!"

    artifacts:
      - build/ios/ipa/*.ipa
      - ios/App/build/ipa/*.ipa
