-- Criar frete de teste com data futura para não ser cancelado automaticamente
INSERT INTO freights (
  producer_id,
  driver_id,
  status,
  cargo_type,
  weight,
  origin_address,
  origin_city,
  origin_state,
  destination_address,
  destination_city,
  destination_state,
  pickup_date,
  delivery_date,
  price,
  distance_km,
  description,
  vehicle_type_required,
  urgency,
  visibility_type
) VALUES (
  '3e6d05fd-3643-4711-bcf2-ad5f955e8d6a',
  'c5dc4f08-0a2b-422a-9811-40232eff167a',
  'LOADED',
  'graos_soja',
  25000,
  'Fazenda Boa Vista, Primavera do Leste, MT',
  'Primavera do Leste',
  'MT',
  'Porto Seco, Cuiabá, MT',
  'Cuiabá',
  'MT',
  '2026-01-15',
  '2026-01-20',
  5000.00,
  251,
  'Frete de teste - Soja para exportação',
  'TRUCK',
  'MEDIUM',
  'ALL'
);