// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shnvtxejjecbnztdbbbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNobnZ0eGVqamVjYm56dGRiYmJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNjAzMzAsImV4cCI6MjA3MjkzNjMzMH0.qcYO3vsj8KOmGDGM12ftFpr0mTQP5DB_0jAiRkPYyFg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: sessionStorage, // Changed from localStorage for better security against XSS attacks
    persistSession: true,
    autoRefreshToken: true,
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    },
    timeout: 30000,
    heartbeatIntervalMs: 30000
  },
  global: {
    headers: {
      'X-Client-Info': 'agriroute-web'
    }
  }
});

// Suppress WebSocket DNS errors in console for SEO/Lighthouse tests
// These errors are handled gracefully by the Supabase client with automatic retries
if (typeof window !== 'undefined') {
  const originalConsoleError = console.error;
  console.error = (...args: any[]) => {
    // Filter out WebSocket DNS resolution errors for Supabase realtime
    const message = args[0]?.toString() || '';
    if (message.includes('WebSocket connection') && 
        message.includes('ERR_NAME_NOT_RESOLVED') && 
        message.includes('supabase.co/realtime')) {
      // Silently ignore - Supabase client handles these with automatic retries
      return;
    }
    // Log all other errors normally
    originalConsoleError.apply(console, args);
  };
}

// Make supabase client available globally for retry logic
(window as any).__supabaseClient = supabase;